# Resourceの定義
resources:
# Git Resourceの定義
- name: kantan_resource
  type: git
  source:
    uri: https://github.com/tomooxy/concourse_test.git
    branch: master
    private_key: ((github-private-key))

- name: kantan_pipeline_resource
  type: git
  source:
    uri: https://github.com/tomooxy/concourse_ci.git
    branch: master
    private_key: ((github-private-key))

- name: kantan_module_resource
  type: git
  source:
    uri: https://github.com/tomooxy/concourse_module.git
    branch: master
    private_key: ((github-private-key))

#- name: pivotal
#  type: cf  # リソースの種類(pcf)
#  source:
#    api: 'api.run.pivotal.io' # pivotalのapi url 
#    username: tomoyuki-ito@exa-corp.co.jp # pcf username
#    password: P@ssw0rd # pcf password
#    skip_cert_check: true      # sslの有効性確認をスキップ    

# Jobの定義
jobs:
- name: kantan_job_production
  public: true # UI上でJobの結果をログイン不要で公開するかどうか
  plan:
  - get: kantan_resource
    trigger: true # Resourceに変更があれば自動でジョブを実行するかどうか
  - get: kantan_pipeline_resource
  - task: build
    params:
      LOCAL-MACHINE-PRIVATE-KEY: ((local-machine-private-key))
    file: kantan_pipeline_resource/tasks/build.yml

- name: kantan_job_production_deploy
  public: true
# serial: true
  plan:
    # 前述のjobであるrails-job-productionで使用したリソースをこちらのコンテナでも使うために、passedを定義します。
    - get: kantan_resource
      passed: [ kantan_job_production ] # kantan_job_productionがパスしたら実行
    - get: kantan_pipeline_resource
    #  passed: [ kantan_job_production ]
    - get: kantan_module_resource
      trigger: true # Resourceに変更があれば自動でジョブを実行するかどうか
    - task: deploy
      params:
        LOCAL-MACHINE-PRIVATE-KEY: ((local-machine-private-key))
      file: kantan_pipeline_resource/tasks/deploy.yml