platform: linux
# 使用するdocker imageを定義
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3-jdk-8
# piplineのresourcesで定義し、jobsのgetで定義したものをコンテナ内で読み込むために、inputを定義する必要があります
# ちなみに、今回はありませんが、コンテナ内で生成したファイルを出力するには、outputを定義します。
inputs:
  - name: kantan_pipeline_resource
  - name: kantan_resource
run:
  path: kantan_pipeline_resource/scripts/build.sh


