platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest
inputs:
  - name: kantan_pipeline_resource
  - name: kantan_resource
run:
  path: kantan_pipeline_resource/scripts/deploy.sh