platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest
inputs:
  - name: pipelines-repo
  - name: capistrano-sample 
run:
  path: pipelines-repo/rails-sample/scripts/deploy.sh