platform: linux
image_resource:
  type: docker-image
  source:
  # repository: centos
  # repository: governmentpaas/cf-cli
    repository: kroniak/ssh-client
    tag: latest
inputs:
  - name: kantan_pipeline_resource
  - name: kantan_resource
run:
  path: kantan_pipeline_resource/scripts/deploy.sh